DEFAULT_WORKER_INSTANCES = 5
DEFAULT_CONSUMER_PREFETCH_COUNT = 10

DEFAULT_CONNECTION_HOST = "localhost"
DEFAULT_CONNECTION_PORT = 5672
DEFAULT_CONNECTION_USER = "guest"
DEFAULT_CONNECTION_PASSWORD = "guest"
